In [1]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [2]:
import numpy as np
import pandas as pd
from keras.callbacks import LearningRateScheduler
from tqdm import tqdm
from keras.layers import Dense, Flatten,Input, Convolution2D, Dropout, Activation, BatchNormalization, Conv2D, MaxPooling2D,AveragePooling2D, Conv2DTranspose, Reshape, UpSampling2D
from keras.models import Sequential, Model, load_model
from keras.regularizers import l2
import tensorflow as tf

%cd /content/drive/My Drive/

/content/drive/My Drive


In [3]:
X = np.load('Picture_feature_4096.npy')
Y = np.load('power_law_comp.npy')
Y_predict = np.load('Decoder_X_4096.npy')

In [8]:
A = Y_predict[0:10,]
B = Y[0:10,]
C = np.pad(B,((0,0),(0,1),(0,4),(0,0)))

In [9]:
print(np.shape(Y_predict))
from tensorflow.keras.optimizers import Adam
from keras import losses
adam = Adam(learning_rate=0.001, beta_1=0.5, beta_2=0.9799, amsgrad=False)

(3753, 4096)


In [13]:
decoder = load_model('Decoder_10ea.h5')

In [17]:
decoder.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 4096)              16781312  
_________________________________________________________________
dense_3 (Dense)              (None, 25440)             104227680 
_________________________________________________________________
reshape_1 (Reshape)          (None, 1, 48, 530)        0         
_________________________________________________________________
batch_normalization_10 (Batc (None, 1, 48, 530)        2120      
_________________________________________________________________
up_sampling2d_5 (UpSampling2 (None, 1, 144, 530)       0         
_________________________________________________________________
conv2d_transpose_10 (Conv2DT (None, 4, 290, 530)       4494930   
_________________________________________________________________
batch_normalization_11 (Batc (None, 4, 290, 530)      

In [12]:
DT = decoder.predict(A)
print(DT)

[[[[4.55341116e-03 0.00000000e+00]
   [2.02142000e-02 1.18939448e-02]
   [4.05205078e-02 0.00000000e+00]
   ...
   [1.46885859e-02 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00]]

  [[0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 1.93262007e-02]
   [0.00000000e+00 2.98777549e-03]
   ...
   [2.13407315e-02 0.00000000e+00]
   [2.56999880e-02 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00]]

  [[0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00]
   [8.57714284e-03 0.00000000e+00]
   ...
   [2.92165764e-02 0.00000000e+00]
   [2.83302739e-02 0.00000000e+00]
   [0.00000000e+00 0.00000000e+00]]

  ...

  [[0.00000000e+00 0.00000000e+00]
   [0.00000000e+00 1.53957438e-02]
   [0.00000000e+00 0.00000000e+00]
   ...
   [0.00000000e+00 0.00000000e+00]
   [1.59808956e-02 0.00000000e+00]
   [5.59500977e-03 0.00000000e+00]]

  [[9.22602322e-03 0.00000000e+00]
   [0.00000000e+00 6.38137572e-05]
   [0.00000000e+00 0.00000000e+00]
   ...
   [0

In [ ]:
np.save("Decoder_predict", DT)